In [1]:
import numpy as np
import pandas as pd

In [2]:
treatments = pd.read_csv('data/mldata.csv')
gexs = pd.read_csv('data/noNormMergedAnd5k.csv')
studies = pd.read_csv('data/metaGXcovarTable.csv')
mgx = pd.merge(gexs, treatments)
mgx = pd.merge(mgx, studies, left_on="sample_name", right_on="sample_name")

In [3]:
mgx.shape, treatments.shape, gexs.shape, studies.shape

((8490, 2929), (9717, 6), (8601, 2896), (9717, 29))

In [4]:
studies.head()

study sample_name sample_type        er       pgr      her2  tumor_size  \
0  GSE25066   GSM615096       tumor  positive  positive  negative         NaN   
1  GSE25066   GSM615097       tumor  positive  positive  negative         NaN   
2  GSE25066   GSM615098       tumor  negative  negative  negative         NaN   
3  GSE25066   GSM615099       tumor  negative  negative  negative         NaN   
4  GSE25066   GSM615100       tumor  positive  positive  negative         NaN   

    T    N  age_at_initial_pathologic_diagnosis  ...  PAM50_prediction  \
0  T2  1.0                                 37.8  ...              LumA   
1  T3  1.0                                 45.8  ...            Normal   
2  T3  0.0                                 40.7  ...             Basal   
3  T2  1.0                                 40.8  ...             Basal   
4  T3  1.0                                 35.5  ...              LumA   

   dlda30_prediction RCB_prediction days_to_death days_to_tumor_recurrence  \
0                 RD        RCB-0/I           NaN                      NaN   
1                 RD        RCB-0/I           NaN                      NaN   
2                pCR     RCB-II/III           NaN                      NaN   
3                pCR        RCB-0/I           NaN                      NaN   
4                 RD     RCB-II/III           NaN                      NaN   

  chemo tamoxifen herceptin replicate Platform  
0   NaN       NaN       NaN     False    GPL96  
1   NaN       NaN       NaN     False    GPL96  
2   NaN       NaN       NaN     False    GPL96  
3   NaN       NaN       NaN     False    GPL96  
4   NaN       NaN       NaN     False    GPL96  

[5 rows x 29 columns]

In [5]:
treatments.head()

sample_name alt_sample_name  recurrence  posOutcome  \
0  CAL_091604_WN405650_LBLPOPII.E10             NaN         0.0         0.0   
1           CAL_LBL_POP_W405609.A10             NaN         0.0         1.0   
2  CAL_091604_WN405650_LBLPOPII.A04             NaN         0.0         0.0   
3           CAL_LBL_POP_W405609.G11             NaN         1.0         1.0   
4   CAL_LBL_POP5_4006154_240.E10_v4             NaN         0.0         0.0   

   hormone  chemo  
0      0.0    0.0  
1      0.0    1.0  
2      1.0    1.0  
3      1.0    0.0  
4      1.0    0.0

In [6]:
gexs.head()

sample_name   CCL5  ESRRA  GAMT  IL12RB1  CSF3R  ITGB1   CBS  SMPDL3B  \
0   DFHCC2_P1   7.97   6.13  4.45     5.04   6.08   6.82  5.58     5.54   
1   DFHCC2_P2  10.19   6.36  4.98     6.99   6.32   4.57  5.64     6.18   
2   DFHCC2_P3   5.36   7.22  5.10     4.19   6.55   4.76  5.91     6.37   
3   DFHCC2_P4   8.94   6.39  5.09     6.14   7.19   4.87  5.54     5.89   
4   DFHCC2_P5   9.43   6.44  5.07     6.16   6.30   6.27  5.56     5.78   

   CNOT9  ...  SIN3B   HPX    GAK  STK10  PHF1  FMO3  CELSR1  ADGRL1  TFEB  \
0   4.92  ...   5.06  4.58   8.34   4.82  7.19  4.06    5.24    5.16  5.71   
1   5.21  ...   4.95  4.60  10.01   6.13  7.83  3.68    4.77    6.13  7.33   
2   4.93  ...   5.72  5.00   9.79   4.72  6.97  3.44    4.55    7.20  5.21   
3   4.30  ...   4.85  4.68   8.62   5.38  7.19  8.30    5.00    5.78  7.10   
4   4.51  ...   5.17  4.60   9.29   5.74  7.98  3.86    5.38    6.01  7.61   

   CX3CL1  
0    5.88  
1    5.90  
2    5.37  
3    5.29  
4    5.44  

[5 rows x 2896 columns]

In [7]:
mgx.head()

sample_name   CCL5  ESRRA  GAMT  IL12RB1  CSF3R  ITGB1   CBS  SMPDL3B  \
0   DFHCC2_P1   7.97   6.13  4.45     5.04   6.08   6.82  5.58     5.54   
1   DFHCC2_P2  10.19   6.36  4.98     6.99   6.32   4.57  5.64     6.18   
2   DFHCC2_P3   5.36   7.22  5.10     4.19   6.55   4.76  5.91     6.37   
3   DFHCC2_P4   8.94   6.39  5.09     6.14   7.19   4.87  5.54     5.89   
4   DFHCC2_P5   9.43   6.44  5.07     6.16   6.30   6.27  5.56     5.78   

   CNOT9  ...  PAM50_prediction  dlda30_prediction  RCB_prediction  \
0   4.92  ...               NaN                NaN             NaN   
1   5.21  ...               NaN                NaN             NaN   
2   4.93  ...               NaN                NaN             NaN   
3   4.30  ...               NaN                NaN             NaN   
4   4.51  ...               NaN                NaN             NaN   

   days_to_death  days_to_tumor_recurrence  chemo_y  tamoxifen  herceptin  \
0            NaN                       NaN      NaN        NaN        NaN   
1            NaN                       NaN      NaN        NaN        NaN   
2            NaN                       NaN      NaN        NaN        NaN   
3            NaN                       NaN      NaN        NaN        NaN   
4            NaN                       NaN      NaN        NaN        NaN   

   replicate  Platform  
0      False    GPL570  
1      False    GPL570  
2      False    GPL570  
3      False    GPL570  
4      False    GPL570  

[5 rows x 2929 columns]

In [8]:
# left_on="sample_name", right_on="sample_name"
treatments[treatments.sample_name == 'DFHCC2_P1']

sample_name alt_sample_name  recurrence  posOutcome  hormone  chemo
233   DFHCC2_P1             NaN         NaN         NaN      0.0    1.0

In [9]:
if not np.any(mgx.sample_name.isnull().values):
    print('There is no unknown (NaN) sample names')
else:
    print('There is UNKNOWN (NaN) sample names')

There is no unknown (NaN) sample names


In [10]:
studies.study.unique(), len(studies.study.unique())

(array(['GSE25066', 'GSE58644', 'GSE32646', 'GSE48091', 'CAL', 'DFHCC',
        'DFHCC2', 'DFHCC3', 'DUKE', 'DUKE2', 'EMC2', 'EORTC10994', 'EXPO',
        'FNCLCC', 'HLP', 'IRB', 'KOO', 'LUND', 'LUND2', 'MAINZ', 'MAQC2',
        'MCCC', 'MDA4', 'MSK', 'MUG', 'NCCS', 'NCI', 'NKI', 'PNC', 'STK',
        'STNO2', 'TRANSBIG', 'UCSF', 'UNC4', 'UNT', 'UPP', 'VDX',
        'METABRIC', 'TCGA'], dtype=object),
 39)

In [11]:
gexs.columns[1:]

Index(['CCL5', 'ESRRA', 'GAMT', 'IL12RB1', 'CSF3R', 'ITGB1', 'CBS', 'SMPDL3B',
       'CNOT9', 'CARD8',
       ...
       'SIN3B', 'HPX', 'GAK', 'STK10', 'PHF1', 'FMO3', 'CELSR1', 'ADGRL1',
       'TFEB', 'CX3CL1'],
      dtype='object', length=2895)

In [12]:
gexs.sample(10)[gexs.columns[1:]]

CCL5     ESRRA      GAMT   IL12RB1     CSF3R      ITGB1       CBS  \
2099  11.152761  6.083128  8.765385  5.844339  9.626168   9.127150  6.417315   
849    9.853310  6.551516  8.230741  5.329124  6.880196   3.935460  6.785289   
4245   8.617194  8.799523  9.779458  7.663840  9.836661   5.037278  8.547128   
8224  11.345549  8.903725  9.137263  7.009132  7.563149  13.523669  8.190709   
1030   6.917000  6.074000  5.973000  6.320000  6.470000   4.091000  7.327000   
7351   9.997171  6.485852  6.816601  6.845164  4.630713   8.629073  4.169514   
3104   7.607743  6.569576  9.520750  5.376528  6.642556   9.633055  6.513613   
1948  10.573051  6.185260  9.806439  5.511208  8.001698   9.307152  6.479566   
7464   9.059431  4.507825  6.314651  7.519057  7.263249   4.743233  5.998448   
6067   9.957242  8.050020  9.332780  6.848397  7.066299  10.296267  6.846111   

       SMPDL3B      CNOT9     CARD8  ...     SIN3B       HPX        GAK  \
2099  6.005751   6.993226  7.377908  ...  7.314494  7.385446   9.846672   
849   4.026800   4.902074  8.983849  ...  9.007588  5.799605   3.711495   
4245  3.163792   5.987215  2.136492  ...  7.295162  6.559373  10.546389   
8224  7.988260   7.820323  9.415358  ...  9.848298  4.897381  11.360443   
1030  2.817000   5.631000  6.632000  ...  7.290000  5.804000   6.974000   
7351  3.226345   4.778245  7.922407  ...  6.275585  5.561448   9.832381   
3104  6.092913   7.598150  5.983687  ...  6.434168  5.809540   9.828097   
1948  7.280429   6.980049  7.408825  ...  7.374407  7.183247  10.058071   
7464  5.581312   7.422015  6.926428  ...  6.803530  9.278418   7.589878   
6067  7.374046  10.108828  8.260082  ...  7.830619  6.752267   7.860910   

          STK10      PHF1      FMO3     CELSR1    ADGRL1      TFEB     CX3CL1  
2099   6.606075  7.116422  5.897593   6.665304  7.865757  5.513161   7.434447  
849    8.776104  8.344296  6.008989   9.082415  8.426684  8.177918   7.842979  
4245   5.970032  8.909820  7.129431   3.465889  9.844532  9.049518   7.125024  
8224  10.440235  9.915052  6.000142  11.551228  9.726362  8.667078  10.789637  
1030   6.717000  5.792000  5.315000   4.721000  7.942000  6.787000   7.275000  
7351   7.338698  8.919683  3.724762   8.048550  5.724685  6.828524   7.080413  
3104   6.186827  6.979591  5.652675   6.063617  7.821947  5.691802   7.486094  
1948   6.491938  7.180050  5.741532   6.116103  8.555949  5.702107   7.044556  
7464   7.395232  8.467452  3.578223   2.654461  7.391262  7.221345   6.638804  
6067   7.237319  7.538052  8.181905   8.949184  7.722951  7.350686   7.082993  

[10 rows x 2895 columns]

In [13]:
gexs.describe()

CCL5        ESRRA         GAMT      IL12RB1        CSF3R  \
count  8601.000000  8601.000000  8601.000000  8601.000000  8601.000000   
mean      8.086327     6.634128     6.979549     5.138451     6.499840   
std       3.070543     2.420020     2.772231     1.886555     2.449691   
min      -2.572060    -1.984273    -3.626250    -0.986000    -1.106386   
25%       7.237578     6.439970     6.024586     4.936504     6.010000   
50%       8.782748     7.036000     7.662573     5.544264     6.986047   
75%      10.031970     7.882551     8.954775     6.140744     7.830154   
max      14.004198    11.783632    12.882226     9.916203    12.901997   

             ITGB1          CBS      SMPDL3B        CNOT9        CARD8  ...  \
count  8601.000000  8601.000000  8601.000000  8601.000000  8601.000000  ...   
mean      7.770467     6.288784     5.614803     6.070438     6.869380  ...   
std       4.037682     2.538027     2.459941     2.510661     2.621375  ...   
min      -1.065301    -2.031060    -1.888012    -0.973616    -1.014585  ...   
25%       4.707304     5.432551     4.397238     4.887525     6.433907  ...   
50%       9.178285     6.699000     6.144902     6.931614     7.340762  ...   
75%      10.241169     7.841049     7.227509     7.662481     8.613467  ...   
max      15.575408    12.249431    11.326423    11.048133    11.400493  ...   

             SIN3B          HPX          GAK        STK10         PHF1  \
count  8601.000000  8601.000000  8601.000000  8601.000000  8601.000000   
mean      7.096347     6.139135     8.427252     6.672794     7.254295   
std       2.488256     2.527273     3.150848     2.494558     2.653597   
min      -2.030203    -2.000000    -0.984539    -0.870994    -0.814003   
25%       6.731431     5.430188     8.451465     6.222934     6.990814   
50%       7.440920     6.403630     9.529896     6.907464     7.690696   
75%       8.428360     7.578248    10.165658     8.113663     8.755392   
max      12.920087    14.740225    13.815315    11.957693    11.647603   

              FMO3       CELSR1       ADGRL1         TFEB       CX3CL1  
count  8601.000000  8601.000000  8601.000000  8601.000000  8601.000000  
mean      5.029505     6.673289     7.203157     6.044892     7.102467  
std       2.114518     3.367085     2.683877     2.252498     2.795164  
min      -1.229091    -2.403712    -1.788306    -0.947150    -3.576145  
25%       4.076902     5.156164     6.781157     5.537422     6.331907  
50%       5.596796     6.262544     7.689014     6.293077     7.484467  
75%       6.269351     9.083163     8.583380     7.422387     8.745853  
max      14.716464    14.566083    13.465508    11.675729    15.263502  

[8 rows x 2895 columns]

In [14]:
gexs.min()

sample_name    CAL_091604_WN405650_LBLPOPII.A02
CCL5                                   -2.57206
ESRRA                                  -1.98427
GAMT                                   -3.62625
IL12RB1                                  -0.986
                             ...               
FMO3                                   -1.22909
CELSR1                                 -2.40371
ADGRL1                                 -1.78831
TFEB                                   -0.94715
CX3CL1                                 -3.57614
Length: 2896, dtype: object

In [15]:
#ngexs = gexs + np.abs()

In [16]:
a = np.random.randn(10, 5)
a

array([[ 1.23639595,  0.82663728,  1.50255013, -0.1286416 ,  0.73205008],
       [-0.93735456,  1.03637314,  0.3959175 ,  0.22668621, -1.6694859 ],
       [-0.70946312,  1.48769282,  1.06503256,  1.66564124, -1.53952951],
       [-0.19595827,  0.18559016, -0.2711938 , -0.04377611,  1.21260797],
       [ 1.56812667, -1.20627905,  0.62897584,  0.80815209,  0.18581902],
       [-0.6118322 ,  0.65970229,  0.88396822,  1.59343025, -0.80957724],
       [-0.30769895,  1.44802909, -0.46475615, -0.30483287, -2.46686025],
       [-1.39448513, -1.16839556, -0.75641921,  1.21455497,  0.20930471],
       [-0.10427023, -0.47053901,  0.19778251,  1.2090715 , -0.2781982 ],
       [ 1.49305141,  0.4471619 ,  0.44642875,  1.18268058, -0.76618271]])

In [17]:
b = (a - a.min(0)) / (a.max(0) - a.min(0))

In [18]:
b

array([[0.88802761, 0.75461676, 1.        , 0.08941567, 0.86939474],
       [0.15429986, 0.83247053, 0.51011613, 0.26974172, 0.21670913],
       [0.23122233, 1.        , 0.80631983, 1.        , 0.25202847],
       [0.40455076, 0.51666063, 0.21479947, 0.13248424, 1.        ],
       [1.        , 0.        , 0.61328635, 0.56483105, 0.72094094],
       [0.26417667, 0.69265064, 0.72616631, 0.9633535 , 0.45041373],
       [0.36683381, 0.98527686, 0.12911333, 0.        , 0.        ],
       [0.        , 0.01406232, 0.        , 0.77107729, 0.72732384],
       [0.43549915, 0.27310606, 0.42240578, 0.76829447, 0.59483108],
       [0.9746591 , 0.61375583, 0.53247644, 0.75490129, 0.46220743]])

In [19]:
a.min(0), a.max(0), (a.max(0) - a.min(0))

(array([-1.39448513, -1.20627905, -0.75641921, -0.30483287, -2.46686025]),
 array([1.56812667, 1.48769282, 1.50255013, 1.66564124, 1.21260797]),
 array([2.9626118 , 2.69397187, 2.25896934, 1.97047411, 3.67946822]))

In [20]:
gexs.shape[0] // 64

134

In [21]:
gexs

sample_name       CCL5      ESRRA       GAMT   IL12RB1      CSF3R  \
0        DFHCC2_P1   7.970000   6.130000   4.450000  5.040000   6.080000   
1        DFHCC2_P2  10.190000   6.360000   4.980000  6.990000   6.320000   
2        DFHCC2_P3   5.360000   7.220000   5.100000  4.190000   6.550000   
3        DFHCC2_P4   8.940000   6.390000   5.090000  6.140000   7.190000   
4        DFHCC2_P5   9.430000   6.440000   5.070000  6.160000   6.300000   
...            ...        ...        ...        ...       ...        ...   
8596  TCGA.WT.AB44   8.547049  10.151302  10.134674  4.042250   7.834439   
8597  TCGA.XX.A899  10.163729   9.559460   8.709830  6.718782  10.500873   
8598  TCGA.XX.A89A   9.749379   9.671293   7.646297  6.907328   9.150540   
8599  TCGA.Z7.A8R5  10.465217   9.842167   9.979954  5.625937   8.963368   
8600  TCGA.Z7.A8R6   8.029492  10.254680   9.217583  4.356616   8.962768   

          ITGB1       CBS   SMPDL3B     CNOT9  ...      SIN3B        HPX  \
0      6.820000  5.580000  5.540000  4.920000  ...   5.060000   4.580000   
1      4.570000  5.640000  6.180000  5.210000  ...   4.950000   4.600000   
2      4.760000  5.910000  6.370000  4.930000  ...   5.720000   5.000000   
3      4.870000  5.540000  5.890000  4.300000  ...   4.850000   4.680000   
4      6.270000  5.560000  5.780000  4.510000  ...   5.170000   4.600000   
...         ...       ...       ...       ...  ...        ...        ...   
8596  13.196616  5.295774  4.523022  5.686470  ...  10.408948   9.794397   
8597  13.437225  8.392487  8.553833  7.508606  ...  10.872081   7.560679   
8598  13.654651  7.123122  7.258349  7.310798  ...  11.070934   6.394660   
8599  12.729982  6.372127  8.839041  6.159538  ...   9.611563  11.839342   
8600  12.811539  7.448246  8.106192  7.639139  ...   9.962328  10.091717   

            GAK      STK10       PHF1      FMO3     CELSR1     ADGRL1  \
0      8.340000   4.820000   7.190000  4.060000   5.240000   5.160000   
1     10.010000   6.130000   7.830000  3.680000   4.770000   6.130000   
2      9.790000   4.720000   6.970000  3.440000   4.550000   7.200000   
3      8.620000   5.380000   7.190000  8.300000   5.000000   5.780000   
4      9.290000   5.740000   7.980000  3.860000   5.380000   6.010000   
...         ...        ...        ...       ...        ...        ...   
8596  10.632670   9.552962  11.374740  2.909965  10.799530   9.697244   
8597  11.169032  10.439618  10.396866  5.889174  12.248275  10.653924   
8598  11.424563  10.545566  10.310895  6.918638  10.822281  11.509023   
8599  11.069019  10.008679  11.238022  6.745810  10.463387   9.927709   
8600  11.432511   9.400299   9.943078  1.780646  12.984728   9.498652   

          TFEB     CX3CL1  
0     5.710000   5.880000  
1     7.330000   5.900000  
2     5.210000   5.370000  
3     7.100000   5.290000  
4     7.610000   5.440000  
...        ...        ...  
8596  8.859378   8.635394  
8597  9.103845  11.098773  
8598  8.906830  10.412393  
8599  9.991851  12.013685  
8600  7.374529   8.293847  

[8601 rows x 2896 columns]

In [36]:
for column_name in gexs.columns:
    if gexs[column_name].dtype is np.dtype(np.float):
        gexs[column_name] = (gexs[column_name] - gexs[column_name].mean()) / gexs[column_name].std()

In [23]:
#normalized_gexs = (gexs - gexs.mean()) / gexs.std()

In [37]:
gexs

sample_name      CCL5     ESRRA      GAMT   IL12RB1     CSF3R  \
0        DFHCC2_P1 -0.037885 -0.208315 -0.912460 -0.052186 -0.171385   
1        DFHCC2_P2  0.685114 -0.113275 -0.721278  0.981444 -0.073413   
2        DFHCC2_P3 -0.887897  0.242094 -0.677992 -0.502742  0.020476   
3        DFHCC2_P4  0.278020 -0.100878 -0.681599  0.530888  0.281733   
4        DFHCC2_P5  0.437601 -0.080217 -0.688813  0.541489 -0.081578   
...            ...       ...       ...       ...       ...       ...   
8596  TCGA.WT.AB44  0.150046  1.453366  1.138118 -0.581060  0.544803   
8597  TCGA.XX.A899  0.676558  1.208805  0.624148  0.837681  1.633280   
8598  TCGA.XX.A89A  0.541615  1.255017  0.240510  0.937623  1.082054   
8599  TCGA.Z7.A8R5  0.774746  1.325625  1.082307  0.258400  1.005648   
8600  TCGA.Z7.A8R6 -0.018510  1.496084  0.807304 -0.414425  1.005403   

         ITGB1       CBS   SMPDL3B     CNOT9  ...     SIN3B       HPX  \
0    -0.235399 -0.279266 -0.030408 -0.458221  ... -0.818383 -0.616924   
1    -0.792649 -0.255625  0.229761 -0.342714  ... -0.862591 -0.609010   
2    -0.745593 -0.149243  0.306998 -0.454238  ... -0.553137 -0.450737   
3    -0.718349 -0.295026  0.111872 -0.705168  ... -0.902780 -0.577355   
4    -0.371616 -0.287146  0.067155 -0.621525  ... -0.774176 -0.609010   
...        ...       ...       ...       ...  ...       ...       ...   
8596  1.343877 -0.391253 -0.443824 -0.152935  ...  1.331295  1.446326   
8597  1.403468  0.828873  1.194756  0.572824  ...  1.517422  0.562481   
8598  1.457317  0.328735  0.668124  0.494037  ...  1.597339  0.101107   
8599  1.228307  0.032838  1.310697  0.035489  ...  1.010835  2.255477   
8600  1.248506  0.456836  1.012784  0.624816  ...  1.151803  1.563971   

           GAK     STK10      PHF1      FMO3    CELSR1    ADGRL1      TFEB  \
0    -0.027691 -0.742734 -0.024229 -0.458500 -0.425677 -0.761271 -0.148676   
1     0.502325 -0.217591  0.216953 -0.638210 -0.565263 -0.399853  0.570526   
2     0.432502 -0.782822 -0.107136 -0.751711 -0.630602 -0.001176 -0.370651   
3     0.061174 -0.518246 -0.024229  1.546686 -0.496955 -0.530262  0.468417   
4     0.273815 -0.373931  0.273480 -0.553084 -0.384098 -0.444565  0.694832   
...        ...       ...       ...       ...       ...       ...       ...   
8596  0.699944  1.154581  1.552777 -1.002375  1.225464  0.929285  1.249496   
8597  0.870172  1.510017  1.184268  0.406555  1.655730  1.285740  1.358027   
8598  0.951271  1.552488  1.151871  0.893411  1.232221  1.604346  1.270562   
8599  0.838431  1.337265  1.501256  0.811677  1.125632  1.015156  1.752259   
8600  0.953794  1.093382  1.013260 -1.536454  1.874452  0.855291  0.590295   

        CX3CL1  
0    -0.437351  
1    -0.430195  
2    -0.619809  
3    -0.648430  
4    -0.594765  
...        ...  
8596  0.548421  
8597  1.429722  
8598  1.184162  
8599  1.757041  
8600  0.426229  

[8601 rows x 2896 columns]

In [35]:
gexs['CCL5'].dtype is np.dtype(np.float)

True

In [32]:
np.dtype(np.float)

dtype('float64')

In [38]:
gexs['CCL5'].mean()

2.3131259854996867e-16